# Generated by Django 3.1.5 on 2021-03-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210319_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='post_pic'),
        ),
    ]
